### ISSUE TITLE
Missing memory.map

### ISSUE THREAD

**Issue by blippy** [sean-lawless/computersystems#1]
If you go to your top level of you project and type `git clean -dfx`, you will find that you will not be able to build the Lab24 game. This is due to the missing memory map.

.gitignore ignores all *.map, which is why it is missing from the repo, but not necessarily your local checkout.

The attached patch (finger crossed) changes .gitignore so that it only ignores kernel maps, not memory maps. The missing memory.map is also instated by the patch.

[memory.log](https://github.com/sean-lawless/computersystems/files/5569386/memory.log)

**Comment by blippy** [comment]
Correction: a better way of ensuring that memory.map isn't excluded is to have the following .gitignore:
```
*.o
*.img
*.elf
*.bin
*.map
!memory.map
```

**Comment by sean-lawless** [comment]
Thank you. Fixed [with this commit](https://github.com/sean-lawless/computersystems/commit/d3314e253e6fa36bc95e9be790ba8b6f6fe56b13)
